#!/usr/bin/env python3
"""Live end-to-end walk of the four states defined in docs/01-按键逻辑.md.

Runs the REAL CLI (scripts/ctrl_swap.py) so every pkexec prompt, keyd
restart and Hyprland bind is the production path. After each transition it
asserts all six observable conditions of the target state:

  1. /etc/keyd/hancore-ctrl-swap.conf content (exact, schema marker included)
  2. keyd service is active
  3. keyd is actually grabbing keyboards (journal has DEVICE: match lines)
  4. Hyprland owns exactly the expected set of voice binds
  5. the two state files match the switch positions
  6. `status` reports remapApplied=true

Walk: ensure -> S1, voice-enable -> S2, enable -> S4, voice-disable -> S3,
disable -> S1. Covers every adjacency: 1<->2, 2<->4, 4<->3, 3<->1, i.e.
each switch toggled in both directions under both states of the other.

Expect FIVE polkit authentication dialogs, one per transition.
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys
import time

REPO = pathlib.Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "ctrl_swap.py"
KEYD_DEST = pathlib.Path("/etc/keyd/hancore-ctrl-swap.conf")
STATE_DIR = pathlib.Path.home() / ".local/state/hancore.keyboard-center"
STATE_FILE = STATE_DIR / "enabled"
VOICE_FILE = STATE_DIR / "voice_enabled"
SCHEMA = "hancore keyboard-center voice-keys/1"
VOICE_DESCRIPTION = "Keyboard key voice dictation"

CONFIGS = {
    (False, False): None,
    (False, True): "capslock = f24\n",
    (True, False): "capslock = layer(control)\nleftcontrol = capslock\n",
    (True, True): "capslock = overload(control, f24)\nleftcontrol = capslock\n",
}

failures: list[str] = []


def check(label: str, ok: bool, detail: str = "") -> None:
    mark = "PASS" if ok else "FAIL"
    print(f"  [{mark}] {label}" + (f" — {detail}" if detail and not ok else ""))
    if not ok:
        failures.append(f"{label}: {detail}")


def run(args: list[str]) -> str:
    return subprocess.run(args, capture_output=True, text=True).stdout.strip()


def owned_binds() -> list[dict]:
    raw = run(["hyprctl", "-j", "binds"])
    try:
        binds = json.loads(raw)
    except json.JSONDecodeError:
        return []
    return [b for b in binds if b.get("description") == VOICE_DESCRIPTION]


def keyd_grabbing() -> bool:
    # keyd enumerates devices asynchronously after start; poll for match
    # lines logged since THIS unit start, not an accumulating window.
    since = run(["systemctl", "show", "keyd", "-p", "ActiveEnterTimestamp", "--value"])
    for _ in range(16):
        log = run(["journalctl", "-u", "keyd", "--since", since, "--no-pager"]) if since else ""
        if "DEVICE: match" in log:
            return True
        time.sleep(0.5)
    return False


def verify_state(name: str, swap: bool, voice: bool) -> None:
    print(f"\n=== state {name} (swap={'on' if swap else 'off'} voice={'on' if voice else 'off'}) ===")
    actual_conf = KEYD_DEST.read_text() if KEYD_DEST.exists() else "<missing>"
    mapping = CONFIGS[(swap, voice)]
    if mapping is None:
        check("keyd config removed", actual_conf == "<missing>", f"got {actual_conf!r}")
    else:
        expected_conf = (
            "# Generated by Omarchy Keyboard Indicator. Do not edit manually.\n"
            f"# schema: {SCHEMA}\n[ids]\n*\n\n[main]\n{mapping}"
        )
        check("keyd config exact", actual_conf == expected_conf, f"got {actual_conf!r}")
        check("keyd service active", run(["systemctl", "is-active", "keyd"]) == "active")
        time.sleep(0.4)
        check("keyd grabbing devices", keyd_grabbing())
    binds = owned_binds()
    want_bind = [(b.get("key"), b.get("release")) for b in binds]
    if voice:
        check("exactly one F24 release bind", want_bind == [("F24", True)], str(want_bind))
    else:
        check("no plugin binds", want_bind == [], str(want_bind))
    check("swap state file", STATE_FILE.exists() == swap)
    check("voice state file", VOICE_FILE.exists() == voice)
    status = json.loads(run(["python3", str(SCRIPT), "status"]))
    check("status remapApplied", status.get("remapApplied") is True, json.dumps(status))
    check("status switches", (status.get("enabled") is swap and status.get("voiceEnabled") is voice))


def transition(cmd: str) -> None:
    print(f"\n>>> ctrl_swap.py {cmd}  (approve the polkit dialog)")
    result = subprocess.run(["python3", str(SCRIPT), cmd], capture_output=True, text=True)
    out = result.stdout.strip()
    print(f"    exit={result.returncode} {out}")
    if result.returncode != 0 or '"error"' in out:
        failures.append(f"{cmd} failed: {out or result.stderr.strip()}")
        raise SystemExit(report())


def report() -> str:
    print("\n================ RESULT ================")
    if failures:
        for item in failures:
            print(f"FAILED: {item}")
        return f"{len(failures)} failure(s)"
    print("ALL FOUR STATES VERIFIED END TO END")
    return "ok"


def main() -> int:
    # Recover from whatever half-state the machine is in right now.
    transition("ensure")
    verify_state("S1 both-off", False, False)

    transition("voice-enable")
    verify_state("S2 voice-only", False, True)

    transition("enable")
    verify_state("S4 swap+voice", True, True)

    transition("voice-disable")
    verify_state("S3 swap-only", True, False)

    transition("disable")
    verify_state("S1 both-off again", False, False)

    summary = report()
    return 0 if summary == "ok" else 1


if __name__ == "__main__":
    sys.exit(main())
