#!/usr/bin/env python3
"""CapsLock <-> Left Ctrl remapping for Omarchy using keyd."""

from __future__ import annotations

import json
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import time

STATE_DIR = pathlib.Path(
    os.environ.get("XDG_STATE_HOME", pathlib.Path.home() / ".local/state")
) / "hancore.keyboard-center"
STATE_FILE = STATE_DIR / "enabled"
KEYD_DEST = pathlib.Path("/etc/keyd/hancore-ctrl-swap.conf")
KEYD_CACHE = pathlib.Path.home() / ".cache/hancore-ctrl-swap-keyd"
VOICE_STATE_FILE = STATE_DIR / "voice_enabled"
VOICE_DESCRIPTION = "CapsLock position voice dictation"
LEGACY_VOICE_DESCRIPTION = "Ctrl Swap voice dictation"
VOICE_BINDINGS = ("F24", "code:66", "CONTROL_L + CONTROL_L")


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def run(*args: str) -> str:
    result = subprocess.run(args, capture_output=True, text=True)
    return result.stdout.strip()


def current_options() -> str:
    try:
        data = json.loads(run("hyprctl", "-j", "getoption", "input:kb_options"))
    except json.JSONDecodeError:
        return ""
    value = data.get("str", "")
    return value if isinstance(value, str) else ""


def clear_legacy_xkb_swap() -> None:
    options = [part.strip() for part in current_options().split(",")
               if part.strip() and part.strip() != "ctrl:swapcaps"]
    safe = ",".join(options).replace("\\", "\\\\").replace('"', '\\"')
    lua = f'hl.config({{ input = {{ kb_options = "{safe}" }} }})'
    result = subprocess.run(["hyprctl", "eval", lua], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "Could not remove the legacy XKB swap")


def root_command(payload: str) -> None:
    if shutil.which("pkexec") is None:
        raise RuntimeError("pkexec is required to install the keyboard remap")
    result = subprocess.run(
        ["pkexec", "bash", "-c", payload], capture_output=True, text=True
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise RuntimeError(detail or "Authentication was cancelled or denied")


def keyd_config(voice_wake: bool = False) -> str:
    caps_mapping = "overload(control, f24)" if voice_wake else "layer(control)"
    return """# Generated by Omarchy Keyboard Center. Do not edit manually.
[ids]
*

[main]
capslock = {caps_mapping}
leftcontrol = capslock
""".format(caps_mapping=caps_mapping)


def keyd_config_matches(voice_wake: bool) -> bool:
    try:
        current = KEYD_DEST.read_text()
    except OSError:
        return False
    normalize = lambda value: "\n".join(
        line for line in value.splitlines() if not line.lstrip().startswith("#")
    )
    return normalize(current) == normalize(keyd_config(voice_wake))


def ensure_keyd_installed(config_path: pathlib.Path) -> bool:
    if shutil.which("keyd") is not None:
        return False
    if shutil.which("git") is None or shutil.which("make") is None:
        raise RuntimeError("keyd is not installed and git/make are unavailable")
    if not (KEYD_CACHE / ".git").exists():
        KEYD_CACHE.parent.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            [
                "git", "clone", "--depth", "1",
                "https://github.com/rvaiya/keyd.git", str(KEYD_CACHE),
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or "Could not download keyd")
    payload = (
        f"set -eu; make -C {shell_quote(str(KEYD_CACHE))} all; "
        f"make -C {shell_quote(str(KEYD_CACHE))} install; "
        f"install -Dm 0644 {shell_quote(str(config_path))} {shell_quote(str(KEYD_DEST))}; "
        "systemctl enable --now keyd; systemctl restart keyd"
    )
    root_command(payload)
    return True


def apply_keyd(enabled: bool, voice_wake: bool = False) -> None:
    config_path = STATE_DIR / "keyd.conf"
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    if enabled:
        config_path.write_text(keyd_config(voice_wake))
        freshly_installed = ensure_keyd_installed(config_path)
        if freshly_installed:
            return
        payload = (
            f"set -eu; install -Dm 0644 {shell_quote(str(config_path))} "
            f"{shell_quote(str(KEYD_DEST))}; systemctl enable --now keyd; "
            "systemctl restart keyd"
        )
    else:
        payload = (
            f"set -eu; rm -f {shell_quote(str(KEYD_DEST))}; "
            "systemctl restart keyd || true"
        )
    root_command(payload)


def persist(enabled: bool) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    if enabled:
        STATE_FILE.write_text("1\n")
    else:
        STATE_FILE.unlink(missing_ok=True)


def enable() -> None:
    apply_keyd(True, VOICE_STATE_FILE.exists())
    clear_legacy_xkb_swap()
    persist(True)
    if VOICE_STATE_FILE.exists():
        voice_enable()


def disable() -> None:
    apply_keyd(False)
    persist(False)


def eval_lua(lua: str) -> None:
    last_detail = "Hyprland rejected the runtime binding"
    for attempt in range(5):
        result = subprocess.run(
            ["hyprctl", "eval", lua], capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            return
        last_detail = (result.stderr or result.stdout).strip() or last_detail
        if attempt < 4:
            time.sleep(0.25)
    raise RuntimeError(last_detail)


def remove_owned_voice_bindings() -> None:
    raw = run("hyprctl", "-j", "binds")
    try:
        binds = json.loads(raw)
    except json.JSONDecodeError:
        binds = []
    if any(item.get("description") in (VOICE_DESCRIPTION, LEGACY_VOICE_DESCRIPTION) for item in binds):
        eval_lua("; ".join(f'hl.unbind("{key}")' for key in VOICE_BINDINGS))


def voice_enable(reconfigure_keyd: bool = True) -> None:
    if shutil.which("voxtype") is None:
        raise RuntimeError("Voxtype is not installed")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    # With the swap active, keyd decides whether the physical CapsLock
    # position is a Ctrl chord or a standalone voice tap.  Without the swap,
    # the transparent physical-key binding below keeps CapsLock's normal
    # behavior while independently waking Voxtype.
    if reconfigure_keyd and STATE_FILE.exists() and not keyd_config_matches(True):
        apply_keyd(True, True)
    remove_owned_voice_bindings()
    eval_lua(
        'hl.bind("F24", hl.dsp.exec_cmd("voxtype record toggle"), '
        '{ release = true, non_consuming = true, description = "CapsLock position voice dictation" }); '
        'hl.bind("code:66", hl.dsp.exec_cmd("voxtype record toggle"), '
        '{ release = true, transparent = true, description = "CapsLock position voice dictation" })'
    )
    VOICE_STATE_FILE.write_text("1\n")


def voice_disable() -> None:
    remove_owned_voice_bindings()
    VOICE_STATE_FILE.unlink(missing_ok=True)
    if STATE_FILE.exists():
        apply_keyd(True, False)


def ensure() -> None:
    # keyd is a system service and survives shell/Hyprland restarts. Only the
    # user-level voice binding needs to be restored here.
    if STATE_FILE.exists() and VOICE_STATE_FILE.exists():
        voice_enable(False)


def status() -> None:
    print(json.dumps({
        "enabled": STATE_FILE.exists() and KEYD_DEST.exists(),
        "backend": "keyd",
        "keydInstalled": shutil.which("keyd") is not None,
        "voiceEnabled": VOICE_STATE_FILE.exists(),
    }))


def main() -> int:
    command = sys.argv[1] if len(sys.argv) > 1 else "status"
    actions = {
        "status": status,
        "enable": enable,
        "disable": disable,
        "ensure": ensure,
        "voice-enable": voice_enable,
        "voice-disable": voice_disable,
    }
    action = actions.get(command)
    if action is None:
        print(f"unknown command: {command}", file=sys.stderr)
        return 2
    try:
        action()
        if command != "status":
            status()
    except Exception as error:
        print(json.dumps({"error": str(error)}))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
