#!/usr/bin/env python3
"""CapsLock <-> Left Ctrl remapping for Omarchy using keyd."""

from __future__ import annotations

import base64
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import time

STATE_DIR = pathlib.Path(
    os.environ.get("XDG_STATE_HOME", pathlib.Path.home() / ".local/state")
) / "hancore.keyboard-center"
STATE_FILE = STATE_DIR / "enabled"
KEYD_DEST = pathlib.Path("/etc/keyd/hancore-ctrl-swap.conf")
KEYD_REPOSITORY = "https://github.com/rvaiya/keyd.git"
# Pin the source that is compiled and installed through pkexec.  The commit
# hash is the integrity check: a moving branch must never reach the root
# command that builds keyd.
KEYD_COMMIT = "f564288ac2b19d2305a5b39023c474805ff8fce5"
VOICE_STATE_FILE = STATE_DIR / "voice_enabled"
VOICE_DESCRIPTION = "CapsLock position voice dictation"
LEGACY_VOICE_DESCRIPTION = "Ctrl Swap voice dictation"
VOICE_BINDINGS = (
    "F24",
    "Caps_Lock",
    "Multi_key",
    "code:66",
    "code:58",
    "CONTROL_L + CONTROL_L",
)


def run(*args: str) -> str:
    result = subprocess.run(args, capture_output=True, text=True)
    return result.stdout.strip()


def current_options() -> str:
    try:
        data = json.loads(run("hyprctl", "-j", "getoption", "input:kb_options"))
    except json.JSONDecodeError:
        return ""
    value = data.get("str", "")
    return value if isinstance(value, str) else ""


def clear_legacy_xkb_swap() -> None:
    options = [part.strip() for part in current_options().split(",")
               if part.strip() and part.strip() != "ctrl:swapcaps"]
    safe = ",".join(options).replace("\\", "\\\\").replace('"', '\\"')
    lua = f'hl.config({{ input = {{ kb_options = "{safe}" }} }})'
    result = subprocess.run(["hyprctl", "eval", lua], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "Could not remove the legacy XKB swap")


PRIVILEGED_HELPER = r'''
import base64
import json
import os
from pathlib import Path
import subprocess
import sys

payload = json.load(sys.stdin)
allowed = {
    "/etc/keyd/hancore-ctrl-swap.conf",
    "/usr/local/bin/keyd",
    "/usr/local/bin/keyd-application-mapper",
    "/usr/local/lib/systemd/system/keyd.service",
}
files = payload.get("files", {})
removals = payload.get("remove", [])
if any(path not in allowed for path in [*files, *removals]):
    raise SystemExit("refusing an unexpected privileged destination")

for path, encoded in files.items():
    destination = Path(path)
    destination.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.hancore-tmp")
    temporary.write_bytes(base64.b64decode(encoded, validate=True))
    os.chmod(temporary, 0o755 if path.endswith(("/keyd", "-application-mapper")) else 0o644)
    os.replace(temporary, destination)
for path in removals:
    Path(path).unlink(missing_ok=True)
if "/usr/local/lib/systemd/system/keyd.service" in files:
    subprocess.run(["systemctl", "daemon-reload"], check=True)
if payload.get("enable"):
    subprocess.run(["systemctl", "enable", "keyd"], check=True)
    subprocess.run(["systemctl", "restart", "keyd"], check=True)
elif payload.get("restart"):
    subprocess.run(["systemctl", "restart", "keyd"], check=True)
'''


def root_command(files: dict[str, bytes] | None = None, remove: tuple[str, ...] = (), *, enable: bool = False, restart: bool = False) -> None:
    if shutil.which("pkexec") is None:
        raise RuntimeError("pkexec is required to install the keyboard remap")
    encoded = {
        path: base64.b64encode(content).decode("ascii")
        for path, content in (files or {}).items()
    }
    payload = json.dumps({"files": encoded, "remove": list(remove), "enable": enable, "restart": restart})
    result = subprocess.run(
        ["pkexec", "python3", "-c", PRIVILEGED_HELPER],
        input=payload,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise RuntimeError(detail or "Authentication was cancelled or denied")


def keyd_config(voice_wake: bool = False) -> str:
    caps_mapping = "overload(control, f24)" if voice_wake else "layer(control)"
    return """# Generated by Omarchy Keyboard Indicator. Do not edit manually.
[ids]
*

[main]
capslock = {caps_mapping}
leftcontrol = capslock
""".format(caps_mapping=caps_mapping)


def keyd_config_matches(voice_wake: bool) -> bool:
    try:
        current = KEYD_DEST.read_text()
    except OSError:
        return False
    normalize = lambda value: "\n".join(
        line for line in value.splitlines() if not line.lstrip().startswith("#")
    )
    return normalize(current) == normalize(keyd_config(voice_wake))


def ensure_keyd_installed(config_path: pathlib.Path) -> bool:
    if shutil.which("keyd") is not None:
        return False
    if shutil.which("git") is None or shutil.which("make") is None:
        raise RuntimeError("keyd is not installed and git/make are unavailable")
    with tempfile.TemporaryDirectory(prefix="hancore-keyd-") as temp_dir:
        checkout_dir = pathlib.Path(temp_dir) / "keyd"
        clone = subprocess.run(
            ["git", "clone", "--no-checkout", "--depth", "1", KEYD_REPOSITORY, str(checkout_dir)],
            capture_output=True,
            text=True,
        )
        if clone.returncode != 0:
            raise RuntimeError(clone.stderr.strip() or "Could not download keyd")
        fetch = subprocess.run(
            ["git", "-C", str(checkout_dir), "fetch", "--depth", "1", KEYD_REPOSITORY, KEYD_COMMIT],
            capture_output=True,
            text=True,
        )
        if fetch.returncode != 0:
            raise RuntimeError(fetch.stderr.strip() or "Could not fetch the pinned keyd revision")
        checkout = subprocess.run(
            ["git", "-C", str(checkout_dir), "checkout", "--force", "--detach", KEYD_COMMIT],
            capture_output=True,
            text=True,
        )
        if checkout.returncode != 0:
            raise RuntimeError(checkout.stderr.strip() or "Could not select the pinned keyd revision")
        status = subprocess.run(
            ["git", "-C", str(checkout_dir), "status", "--porcelain", "--untracked-files=all"],
            capture_output=True,
            text=True,
        )
        if status.returncode != 0 or status.stdout.strip():
            raise RuntimeError("keyd checkout contains unexpected local changes")
        build = subprocess.run(["make", "-C", str(checkout_dir), "all"], capture_output=True, text=True)
        if build.returncode != 0:
            raise RuntimeError(build.stderr.strip() or "Could not build keyd")
        files = {
            "/usr/local/bin/keyd": (checkout_dir / "bin/keyd").read_bytes(),
            "/usr/local/bin/keyd-application-mapper": (checkout_dir / "bin/keyd-application-mapper").read_bytes(),
            "/usr/local/lib/systemd/system/keyd.service": (
                "[Unit]\nDescription=key remapping daemon\n\n"
                "[Service]\nType=simple\nExecStart=/usr/local/bin/keyd\n\n"
                "[Install]\nWantedBy=multi-user.target\n"
            ).encode(),
            str(KEYD_DEST): config_path.read_bytes(),
        }
    root_command(files, enable=True)
    return True


def apply_keyd(enabled: bool, voice_wake: bool = False) -> None:
    config_path = STATE_DIR / "keyd.conf"
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    if enabled:
        config_path.write_text(keyd_config(voice_wake))
        freshly_installed = ensure_keyd_installed(config_path)
        if freshly_installed:
            return
        root_command({str(KEYD_DEST): config_path.read_bytes()}, enable=True)
    else:
        root_command(remove=(str(KEYD_DEST),), restart=True)


def persist(enabled: bool) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    if enabled:
        STATE_FILE.write_text("1\n")
    else:
        STATE_FILE.unlink(missing_ok=True)


def enable() -> None:
    apply_keyd(True, VOICE_STATE_FILE.exists())
    clear_legacy_xkb_swap()
    persist(True)
    if VOICE_STATE_FILE.exists():
        voice_enable()


def disable() -> None:
    apply_keyd(False)
    persist(False)
    if VOICE_STATE_FILE.exists():
        voice_enable(False)


def eval_lua(lua: str) -> None:
    last_detail = "Hyprland rejected the runtime binding"
    for attempt in range(5):
        result = subprocess.run(
            ["hyprctl", "eval", lua], capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            return
        last_detail = (result.stderr or result.stdout).strip() or last_detail
        if attempt < 4:
            time.sleep(0.25)
    raise RuntimeError(last_detail)


def remove_owned_voice_bindings() -> None:
    raw = run("hyprctl", "-j", "binds")
    try:
        binds = json.loads(raw)
    except json.JSONDecodeError:
        binds = []
    if any(item.get("description") in (VOICE_DESCRIPTION, LEGACY_VOICE_DESCRIPTION) for item in binds):
        eval_lua("; ".join(f'hl.unbind("{key}")' for key in VOICE_BINDINGS))


def voice_enable(reconfigure_keyd: bool = True) -> None:
    if shutil.which("voxtype") is None:
        raise RuntimeError("Voxtype is not installed")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    # With the swap active, keyd decides whether the physical CapsLock
    # position is a Ctrl chord or a standalone voice tap.  Without the swap,
    # the transparent physical-key binding below keeps CapsLock's normal
    # behavior while independently waking Voxtype.
    if reconfigure_keyd and STATE_FILE.exists() and not keyd_config_matches(True):
        apply_keyd(True, True)
    remove_owned_voice_bindings()
    if STATE_FILE.exists():
        binding = (
            'hl.bind("F24", hl.dsp.exec_cmd("voxtype record toggle"), '
            '{ release = true, non_consuming = false, '
            'description = "CapsLock position voice dictation" })'
        )
    else:
        binding = (
            'hl.bind("Caps_Lock", hl.dsp.exec_cmd("voxtype record toggle"), '
            '{ transparent = true, '
            'description = "CapsLock position voice dictation" }); '
            'hl.bind("Multi_key", hl.dsp.exec_cmd("voxtype record toggle"), '
            '{ transparent = true, '
            'description = "CapsLock position voice dictation" })'
        )
    eval_lua(binding)
    VOICE_STATE_FILE.write_text("1\n")


def voice_disable() -> None:
    remove_owned_voice_bindings()
    VOICE_STATE_FILE.unlink(missing_ok=True)
    if STATE_FILE.exists():
        apply_keyd(True, False)


def ensure() -> None:
    # keyd is a system service and survives shell/Hyprland restarts, but the
    # user-level voice binding must be restored independently of the optional
    # Ctrl/CapsLock swap.  In particular, voice_enabled can remain set when
    # the swap itself is disabled.
    if VOICE_STATE_FILE.exists():
        voice_enable(STATE_FILE.exists())


def status() -> None:
    print(json.dumps({
        "enabled": STATE_FILE.exists() and KEYD_DEST.exists(),
        "backend": "keyd",
        "keydInstalled": shutil.which("keyd") is not None,
        "voiceEnabled": VOICE_STATE_FILE.exists(),
    }))


def main() -> int:
    command = sys.argv[1] if len(sys.argv) > 1 else "status"
    actions = {
        "status": status,
        "enable": enable,
        "disable": disable,
        "ensure": ensure,
        "voice-enable": voice_enable,
        "voice-disable": voice_disable,
    }
    action = actions.get(command)
    if action is None:
        print(f"unknown command: {command}", file=sys.stderr)
        return 2
    try:
        action()
        if command != "status":
            status()
    except Exception as error:
        print(json.dumps({"error": str(error)}))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
